### PR TITLE
Upgrade Kafka version to 1.0.0 #366

### PR DESCRIPTION
**Pull request by cstub**
* Upgrade Kafka-clients to version `1.0.0` (see [Release Notes](https://archive.apache.org/dist/kafka/1.0.0/RELEASE_NOTES.html))
* Upgrade Scalatest-embedded-kafka to version `1.0.0`

Refs #366

### CODE REVIEW

**Comment by fmsbeekmans** [comment]
How is this going, do you want some help?

**Comment by cstub** [comment]
I totally missed that there is a conflict. I will resolve it.

**Comment by fmsbeekmans** [comment]
Is there a new release planned?

**Comment by ktoso** [comment]
Yeah, soon. Not super sure when exactly

**Pull request merged**
