### PR TITLE
Cross-build for Scala 2.12

### PR DESCRIPTION
**Pull request by cb372**
* Bump akka to 2.4.12
* Upgrade ScalaTest to 3.0.1

Note that this PR is currently blocked by manub/scalatest-embedded-kafka#48

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks :-) This'll resolve https://github.com/akka/reactive-kafka/issues/256 (which I opened before looking at PRs)

**Comment by kciesielski** [comment]
This PR depends on https://github.com/manub/scalatest-embedded-kafka/issues/48 (scalatest-embedded-kafka for 2.12 requires Kafka 2.12)

**Comment by johanandren** [comment]
I have backported these changes on top of v0.13, and run tests again a snapshots of the scalatest-embedded-kafka and kafka verifying that the tests pass also for 2.12, the artifact is now on maven central. Will push a tag for it soon so that the changes that was needed can be seen.

**Comment by analytically** [comment]
Akka 2.4.14 is out :-)

**Comment by leachbj** [comment]
Kafka 0.10.1.1 rc0 is out and includes a 2.12 build, the release bundle is available at http://home.apache.org/~guozhang/kafka-0.10.1.1-rc0/ but its just as easy to build locally `./gradlew install_2_1` from the `0.10.1.1-rc0` tag.

**Comment by manub** [comment]
`scalatest-embedded-kafka` version `0.11.0` is now compiled for both Scala 2.11 and 2.12.

**Comment by cb372** [comment]
Closing because superseded by #264

**Pull request closed without merging**
