### PR TITLE
Fix grammar and minor typos in the Consumer documentation

### PR DESCRIPTION
**Pull request by calvinlfer**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @calvinlfer,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by patriknw** [comment]
LGTM after CLA
Thanks for contributing, @calvinlfer

**Comment by calvinlfer** [comment]
Hey @patriknw, I have signed the CLA but it doesn't seem to be passing the check

**Comment by calvinlfer** [comment]
I provide my details and click sign but it appears to refresh the page and doesn't seem to do much more than that. Is it because I haven't put my full name on GitHub? Or is there something wrong with my email?

**Comment by patriknw** [comment]
I don't see your name in the CLA list. yet. I don't think there should be any delays for that. I don't know, right now.

**Comment by calvinlfer** [comment]
I was able to sign the Scala CLA but the Lightbend CLA keeps redirecting me back to the same page. Using the same details in both places :-(

**Comment by patriknw** [comment]
strange, I'll ask around if it's broken

**Comment by calvinlfer** [comment]
Thanks!

**Comment by calvinlfer** [comment]
I managed to sign it today and got the proper response :-)

**Comment by calvinlfer** [comment]
All good now

**Comment by patriknw** [comment]
@calvinlfer Thanks for contributing!

**Pull request merged**
