### PR TITLE
Kafka 1.0.0 -> 1.0.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
👍

**Comment by sullis** [comment]
ping @ktoso

**Comment by ktoso** [comment]
I’m not up to date with changes in 1.0.1 but I assume it’s fine.
@kciesielski or @2m or @johanandren may want to confirm LGTM

**Comment by kciesielski** [comment]
LGTM, as far as I checked the release notes for 1.0.1 it should be compatible.

**Pull request merged**
