### PR TITLE
Upgrade to kafka client 0.10.0.1

### PR DESCRIPTION
**Pull request by 13h3r**

### CODE REVIEW

**Comment by 13h3r** [comment]
The problem is in `"net.manub" %% "scalatest-embedded-kafka"`

**Comment by 13h3r** [comment]
Here it is the fix - https://github.com/manub/scalatest-embedded-kafka/pull/31
Waiting to be merged and next bump version in deps

**Comment by 13h3r** [comment]
Done

**Comment by kciesielski** [comment]
LGTM

**Pull request merged**
