### PR TITLE
Synchronize production with consumption of messages

### PR DESCRIPTION
**Pull request by nafshartous**
Replace method `produceMessages` with `produce` (returns a `Future`) and invoke `Await` on the result.  Using a `Future` was suggested by @13h3r.

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @nafshartous,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by drewhk** [comment]
Ok, so this is for testing only. I have nothing against it.

**Comment by patriknw** [comment]
LGTM

**Comment by 13h3r** [comment]
LGTM

**Pull request merged**
