### PR TITLE
Switch to sbt 0.13.13

### PR DESCRIPTION
**Pull request by kciesielski**

### CODE REVIEW

**Comment by patriknw** [comment]
LGTM

**Comment by kciesielski** [comment]
Build fails due to unresolved artifact:
```[error] (core/*:update) sbt.ResolveException: download failed: javax.jms#jms;1.1!jms.jar```
I can't find it locally in compile/test dependencies, is this something Travis-specific?

**Comment by analytically** [comment]
Is JMS still needed??

**Comment by savulchik** [comment]
I encountered the same issue in another project where I tried to exclude `slf4j-log4j12` binding from `kafka` artifact without also excluding `log4j`. If I also exclude `log4j` the problem is gone.
```
libraryDependencies ++= Seq(
  "org.apache.kafka" %% "kafka" % "0.10.1.0"
    exclude("org.slf4j", "slf4j-log4j12"), 
    // exclude("log4j", "log4j"),
    "org.slf4j" % "log4j-over-slf4j" % "1.7.21"

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: javax.jms#jms;1.1!jms.jar
[warn] 	:: com.sun.jdmk#jmxtools;1.2.1!jmxtools.jar
[warn] 	:: com.sun.jmx#jmxri;1.2.1!jmxri.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[trace] Stack trace suppressed: run last core/*:update for the full output.
[error] (core/*:update) sbt.ResolveException: download failed: javax.jms#jms;1.1!jms.jar
```
[Here](http://search.maven.org/#artifactdetails%7Cnet.manub%7Cscalatest-embedded-kafka_2.11%7C0.10.0%7Cjar) I see that scalatest-embedded-kafka_2.11 excludes only `slf4j-log4j12` leaving `log4j`.

**Comment by kciesielski** [comment]
@savulchik Thanks for this insight. It's still unclear to me what it has to do with switching to SBT 0.13.13. We use scalatest-embedded-kafka in the master branch and it gets build correctly. I'll try to exclude log4j and we'll see if that helps :)

**Comment by savulchik** [comment]
@kciesielski I noticed that `scalatest-embedded-kafka` already uses `sbt 0.13.13` but doesn't have the problem. I guess it is due to alternative artifacts resolver used - `sbt-coursier`.

**Pull request merged**
