### PR TITLE
Manual commits are not handled appropriately after a consumer rebalance in 0.8 branch

### PR DESCRIPTION
**Pull request by evans-ye**

### CODE REVIEW

**Comment by typesafehub-validator** [comment]
Hi @evans-ye,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kciesielski** [comment]
@evans-ye Thanks :) The fix looks good. I wrote a failing test for #141 and it passes with this update. Please complete the CLA validation and I'll merge.

**Comment by evans-ye** [comment]
Thanks for writing the test.
I've just signed the CLA. 
Please tell me if any further step needed.

**Comment by kciesielski** [comment]
It's ok, thanks again.

**Pull request merged**
