### PR TITLE
Debug and activate test "consume and commit in batches"

### PR DESCRIPTION
**Pull request by nafshartous**
Debugged and removed `ignore` for test "consume and commit in batches"
- The problem was that the `consumerSettings` was re-used.  This caused intermittent Travis failures when resuming consumption ("consumer actor terminated").

### CODE REVIEW

**Comment by patriknw** [comment]
I don't understand how this could be a problem. `ConsumerSettings` is immutable and can be shared. What am I missing?

**Comment by nafshartous** [comment]
Could it be that cancelling the stream somehow requires a new `ConsumerSettings` to be created for resuming consumption ?  

To understand further, I could recreate a debug PR after this one is closed.

**Comment by patriknw** [comment]
I don't see anything in ConsumerSettings that would explain that.
You can just push more commits to this branch to trigger new travis builds.

**Comment by nafshartous** [comment]
I reproduced the error not re-using `consumerSettings` so the root cause is something else.

What can cause the 
 ```
expected OnNext, found OnError(java.lang.Exception: Consumer actor terminated
```

I've only seen this on Travis builds.

**Comment by nafshartous** [comment]
Reproduced the same error locally so its not specific to Travis.

**Comment by nafshartous** [comment]
In the intermittent failure case I'm seeing these additional lines output 

```
00:49:32.302 WARN  akka.kafka.KafkaConsumerActor - Consumer interrupted with WakeupException after timeout. Message: null. Current value of akka.kafka.consumer.wakeup-timeout is 3000 milliseconds

00:49:35.318 WARN  akka.kafka.KafkaConsumerActor - Consumer interrupted with WakeupException after timeout. Message: null. Current value of akka.kafka.consumer.wakeup-timeout is 3000 milliseconds

00:49:38.341 ERROR akka.kafka.KafkaConsumerActor - WakeupException limit exceeded, stopping.

SingleSourceLogic.postStop: stopping consumer
 
```
then the test fails because the consumer is stopped

```
[info] - must consume and commit in batches *** FAILED ***

[info]   java.lang.AssertionError: expected OnNext, found OnError(java.lang.Exception: Consumer actor terminated
```

Does anyone know what could be triggering the `WakeupException` ?

**Comment by patriknw** [comment]
WakeupTimeout is triggered when consumer can't connect to Kafka server, or server not ready yet. It's retried several times before giving up. See KafkaConsumerActor. Increasing the timeout and/or number of retries might be needed on Travis.

**Comment by nafshartous** [comment]
I tried yesterday setting `wakeUpTimeout` up to 4 seconds.  Error is still happening about 1 in 12 tries, very random.

**Comment by nafshartous** [comment]
I'm now getting an `sbt` related error in the Travis build

```
Downloading sbt launcher for 0.13.11:
  From  http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.11/sbt-launch.jar
    To  /home/travis/.sbt/launchers/0.13.11/sbt-launch.jar
Download failed. Obtain the jar manually and place it at /home/travis/.sbt/launchers/0.13.11/sbt-launch.jar
restoring stty: 500:5:bf:8a3b:3:1c:7f:15:4:0:1:0:11:13:1a:0:12:f:17:16:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0:0
The command "eval $SCRIPT" exited with 1.
cache.2
store build cache
0.00s
1.21snothing changed, not updating cache
Done. Your build exited with 1.
```

Can someone install the missing Jar ?

**Pull request closed without merging**
